### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by rpratt20** [KM4YRI/pyFldigi#6]
I was having trouble using functions and went back to start over.  I found the first issue is that I can not link my code to fldigi.  Fldigi will start and stop but will not execute anything in between.  The command app.is_running() returns false.  Here is the error from python. Windows 10 64 bit.  Fldigi-4.1.04.01

Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\rprat\Anaconda3\lib\site-packages\urllib3\connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "C:\Users\rprat\Anaconda3\lib\site-packages\urllib3\util\connection.py", line 84, in create_connection
    raise err
  File "C:\Users\rprat\Anaconda3\lib\site-packages\urllib3\util\connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rprat\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "C:\Users\rprat\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\rprat\Anaconda3\lib\http\client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\rprat\Anaconda3\lib\http\client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\rprat\Anaconda3\lib\http\client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\rprat\Anaconda3\lib\http\client.py", line 1016, in _send_output
    self.send(msg)
  File "C:\Users\rprat\Anaconda3\lib\http\client.py", line 956, in send
    self.connect()
  File "C:\Users\rprat\Anaconda3\lib\site-packages\urllib3\connection.py", line 184, in connect
    conn = self._new_conn()
  File "C:\Users\rprat\Anaconda3\lib\site-packages\urllib3\connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000002810F7C6B00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rprat\Anaconda3\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\rprat\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "C:\Users\rprat\Anaconda3\lib\site-packages\urllib3\util\retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=7362): Max retries exceeded with url: // (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002810F7C6B00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rprat\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\rprat\Anaconda3\lib\site-packages\pyfldigi\client\txmonitor.py", line 170, in run
    state = self.clientObj.main.get_trx_state()
  File "C:\Users\rprat\Anaconda3\lib\site-packages\pyfldigi\client\main.py", line 287, in get_trx_state
    state = str(self.client.main.get_trx_status()).upper()
  File "C:\Users\rprat\Anaconda3\lib\xmlrpc\client.py", line 1112, in __call__
    return self.__send(self.__name, args)
  File "C:\Users\rprat\Anaconda3\lib\xmlrpc\client.py", line 1452, in __request
    verbose=self.__verbose
  File "C:\Users\rprat\Anaconda3\lib\site-packages\pyfldigi\client\transport.py", line 39, in request
    resp = requests.post(url, data=request_body, headers=headers)
  File "C:\Users\rprat\Anaconda3\lib\site-packages\requests\api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\rprat\Anaconda3\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\rprat\Anaconda3\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\rprat\Anaconda3\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\rprat\Anaconda3\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=7362): Max retries exceeded with url: // (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002810F7C6B00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

**Comment by rpratt20** [comment]
I have the connection partially working.  The above errors now only occur during shutdown of fldigi with the interface.  However, the program below will only transmit one part and then refuses to transmit again. After the client ends fldigi will not transmit macro text until restarting.  For demo run the code below and then press the CQ macro.
import time
import pyfldigi

# Load Module and start instance of Application Monitor
app = pyfldigi.ApplicationMonitor()
app.start()
time.sleep(2)
print(app.is_running())  #This does not work - Returns False when running
# Short names for functions.
c = pyfldigi.Client()
m = c.main
t = c.text

# Start testing commands
mdm = c.modem.name
m.squelch_level = 0     #Allows status fields to populate.
status1 = m.status1
status2 = m.status2
m.squelch_level = 10
print(status1 , status2)
tx_text = mdm + status1 + status2

t.add_tx(tx_text)
m.tx()
m.rx()            # Most often everything stops at this point

m.send(' KJ0RE Transmit 1st' + status1 + ' ' + status2 +' '+mdm+' KJ0RE', timeout=15)

out = mdm + status1 + status2 + 'KJ0re' + '73'
print(out)
t.add_tx(out)

m.tx()
m.rx()
